<a href="https://colab.research.google.com/github/Evsstah/data_analysis/blob/master/num2(3_%D0%B1%D0%B0%D0%BB%D0%BB%D0%B0).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Генерация массивов
m1 = np.random.randint(10, 51, 20)
m2 = np.random.randint(1, 11, 10)

print("Исходные массивы:")
print(f"m1 = {m1}")
print(f"m2 = {m2}")

# 1. Формируем массив m3
m3 = np.setxor1d(m1, m2)
print(f"\n1. Массив m3 (элементы только в m1 или только в m2): {m3}")

# 2. Заменяем в m1 все значения, кратные 3 или 2 на число 1
m1_modified = m1.copy()
mask = (m1_modified % 4 == 0) & (m1_modified % 3 == 0)
m1_modified[mask] = 100
print(f"\n2. Массив m1 после замены кратных 2 или 3 на 1: {m1_modified}")

# 3. Сливаем массивы m1 и m2 в один и преобразовать в матрицу 4х5
merged_array = np.concatenate((m1_modified, m2))

# Проверяем размер
if len(merged_array) != 20:
    merged_array = np.resize(merged_array, 20)

matrix_4x5 = merged_array.reshape(4, 5)
print(f"\n3. Матрица 4х5 (после преобразования m1):")
print(matrix_4x5)

# 4. Удалить из матрицы 1 и 4 столбцы
matrix_without_cols = matrix_4x5[:, [1, 2, 4]]
print(f"\n4. Матрица после удаления 1 и 4 столбцов:")
print(matrix_without_cols)

# 5. Транспонировать полученную матрицу
transposed_matrix = matrix_without_cols.T
print(f"\n5. Транспонированная матрица:")
print(transposed_matrix)

Исходные массивы:
m1 = [ 5  1 10  6  9  1 10  3  7  4]
m2 = [9 3 5 3 7 5 9 7 2 4]

1. Массив m3 (элементы только в m1 или только в m2): [ 1  2  6 10]

2. Массив m1 после замены кратных 2 или 3 на 1: [5 1 1 1 1 1 1 1 7 1]

3. Матрица 4х5 (после преобразования m1):
[[5 1 1 1 1]
 [1 1 1 7 1]
 [9 3 5 3 7]
 [5 9 7 2 4]]

4. Матрица после удаления 1 и 4 столбцов:
[[1 1 1]
 [1 1 1]
 [3 5 7]
 [9 7 4]]

5. Транспонированная матрица:
[[1 1 3 9]
 [1 1 5 7]
 [1 1 7 4]]
